apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-conduit-graphql-config
  namespace: core-insights-nebula
data:
  GRAPHQL_ENDPOINT: "https://192.168.1.230/api"
  GRAPHQL_USERNAME: "integration"
  GRAPHQL_PASSWORD: "Nebula=2020"
