apiVersion: v1
kind: ConfigMap
metadata:
  name: nebula-conduit-s3-config
  namespace: core-insights-nebula
data:
  S3_ENDPOINT: "192.168.1.40:9000"
  S3_BUCKET: "nebula-configurations"
  S3_USE_SSL: "false"
  S3_REGION: "us-east-1"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin123"
