apiVersion: v1
kind: Service
metadata:
  name: nebula-conduit
  namespace: core-insights-nebula
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: nebula-conduit
