server:
  host: "localhost"
  port: 8080

auth:
  jwt_secret: "your_secure_secret_here"
  token_expiry_hours: 24

database:
  path: "Nebula.Conduit.db"

paths:
  python_scripts_home: "C:/nebula.rivulet/fabric/build/lib/algorithms"
  allowed_paths:
    # - "/opt/pyexec/scripts"
    - "C:/nebula.rivulet/fabric/build/lib/algorithms"
